import Nav from '@/components/nav/pages'
import Footer from '@/components/footer/pages'
import '../globals.css'
import { Inter } from 'next/font/google'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=' bg-slate-800 text-white'>
        <Nav/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
